### ISSUE TITLE
[Anon] Bug report: TWD_Neutral.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/the-walking-dead#12]
**File:** TWD_Neutral.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Patrick, Scavenger (20 Points):

Melee: 1 White
Shoot: 1 Red
Defense: 2 Red

Nerve: Medium
Health: 4
Pack: 2

Character: Bruiser
Faction: Neutral

**Comment by mugginns** [comment]
I can't find the bug in this one. Closing
