### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by skyengel** [BSData/the-walking-dead#2]
@amis92

Hi,
i want to help to update the Walking Dead All out War File.

**Comment by amis92** [comment]
Hello, @skyengel. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
