### ISSUE TITLE
[Anon] Bug report: TWD_Ricks_Group.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/the-walking-dead#3]
**File:** TWD_Ricks_Group.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** Yes

**Description:** Sophia in rick's group is set as a support but she is a runner. 
The kingdom is not a stand alone faction and Can be played with rick's group Inti rules change.
The neutral faction Can be played with any other faction.

**Comment by mugginns** [comment]
Fixed
