### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by mugginns** [BSData/the-walking-dead#4]
Hi, is anyone planning to update this file for new releases? I can work on it, just wanted to make sure it wasn't being done by someone else.

**Comment by Fleafa** [comment]
I just don't have the time right now. Skyengel originally took over from me, and I'd be happy for you to take it over.

**Comment by mugginns** [comment]
NP, I'll do some work on it. Can you add me to the team or whatever?

**Comment by Fleafa** [comment]
I don't have permissions to do that, unfortunately. You'll need to apply through BSData.
https://github.com/BSData/bsdata/wiki

**Comment by Fleafa** [comment]
Excellent! Thanks for taking it on. I am way behind on releases now, so would lack the reference even if I had the time!
